--
-- PostgreSQL database dump
--

-- Dumped from database version 12.1
-- Dumped by pg_dump version 12.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Observations; Type: TABLE; Schema: public; Owner: alex
--

CREATE TABLE public."Observations" (
    id integer NOT NULL,
    user_id integer NOT NULL,
    date timestamp without time zone NOT NULL,
    plant_id integer NOT NULL,
    notes character varying(2500)
);


ALTER TABLE public."Observations" OWNER TO alex;

--
-- Name: Observations_id_seq; Type: SEQUENCE; Schema: public; Owner: alex
--

CREATE SEQUENCE public."Observations_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Observations_id_seq" OWNER TO alex;

--
-- Name: Observations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: alex
--

ALTER SEQUENCE public."Observations_id_seq" OWNED BY public."Observations".id;


--
-- Name: Plants; Type: TABLE; Schema: public; Owner: alex
--

CREATE TABLE public."Plants" (
    id integer NOT NULL,
    user_id integer NOT NULL,
    name character varying(120) NOT NULL,
    latin_name character varying(120) NOT NULL,
    description character varying(2500) NOT NULL,
    image_link character varying(500) NOT NULL
);


ALTER TABLE public."Plants" OWNER TO alex;

--
-- Name: Plants_id_seq; Type: SEQUENCE; Schema: public; Owner: alex
--

CREATE SEQUENCE public."Plants_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Plants_id_seq" OWNER TO alex;

--
-- Name: Plants_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: alex
--

ALTER SEQUENCE public."Plants_id_seq" OWNED BY public."Plants".id;


--
-- Name: Users; Type: TABLE; Schema: public; Owner: alex
--

CREATE TABLE public."Users" (
    id integer NOT NULL,
    name character varying(120) NOT NULL,
    username character varying(120) NOT NULL,
    user_id character varying(120) NOT NULL,
    date_added timestamp without time zone NOT NULL,
    role character varying(120) NOT NULL
);


ALTER TABLE public."Users" OWNER TO alex;

--
-- Name: Users_id_seq; Type: SEQUENCE; Schema: public; Owner: alex
--

CREATE SEQUENCE public."Users_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Users_id_seq" OWNER TO alex;

--
-- Name: Users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: alex
--

ALTER SEQUENCE public."Users_id_seq" OWNED BY public."Users".id;


--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: alex
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


ALTER TABLE public.alembic_version OWNER TO alex;

--
-- Name: Observations id; Type: DEFAULT; Schema: public; Owner: alex
--

ALTER TABLE ONLY public."Observations" ALTER COLUMN id SET DEFAULT nextval('public."Observations_id_seq"'::regclass);


--
-- Name: Plants id; Type: DEFAULT; Schema: public; Owner: alex
--

ALTER TABLE ONLY public."Plants" ALTER COLUMN id SET DEFAULT nextval('public."Plants_id_seq"'::regclass);


--
-- Name: Users id; Type: DEFAULT; Schema: public; Owner: alex
--

ALTER TABLE ONLY public."Users" ALTER COLUMN id SET DEFAULT nextval('public."Users_id_seq"'::regclass);


--
-- Data for Name: Observations; Type: TABLE DATA; Schema: public; Owner: alex
--

COPY public."Observations" (id, user_id, date, plant_id, notes) FROM stdin;
\.


--
-- Data for Name: Plants; Type: TABLE DATA; Schema: public; Owner: alex
--

COPY public."Plants" (id, user_id, name, latin_name, description, image_link) FROM stdin;
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: alex
--

COPY public."Users" (id, name, username, user_id, date_added, role) FROM stdin;
1	Alex Sandberg	Alex Sandberg	google-oauth2|100849711247597969416	2020-02-09 18:19:28.480359	Admin
27	asb163@yahoo.com	alexsb163	auth0|5e45c2ff8a409e0e62024a50	2020-02-14 17:42:28.219483	Public
\.


--
-- Data for Name: alembic_version; Type: TABLE DATA; Schema: public; Owner: alex
--

COPY public.alembic_version (version_num) FROM stdin;
7225f407d169
\.


--
-- Name: Observations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: alex
--

SELECT pg_catalog.setval('public."Observations_id_seq"', 4, true);


--
-- Name: Plants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: alex
--

SELECT pg_catalog.setval('public."Plants_id_seq"', 13, true);


--
-- Name: Users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: alex
--

SELECT pg_catalog.setval('public."Users_id_seq"', 27, true);


--
-- Name: Observations Observations_pkey; Type: CONSTRAINT; Schema: public; Owner: alex
--

ALTER TABLE ONLY public."Observations"
    ADD CONSTRAINT "Observations_pkey" PRIMARY KEY (id);


--
-- Name: Plants Plants_pkey; Type: CONSTRAINT; Schema: public; Owner: alex
--

ALTER TABLE ONLY public."Plants"
    ADD CONSTRAINT "Plants_pkey" PRIMARY KEY (id);


--
-- Name: Users Users_pkey; Type: CONSTRAINT; Schema: public; Owner: alex
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY (id);


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: alex
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: Observations Observations_plant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: alex
--

ALTER TABLE ONLY public."Observations"
    ADD CONSTRAINT "Observations_plant_id_fkey" FOREIGN KEY (plant_id) REFERENCES public."Plants"(id);


--
-- Name: Observations Observations_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: alex
--

ALTER TABLE ONLY public."Observations"
    ADD CONSTRAINT "Observations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."Users"(id);


--
-- Name: Plants Plants_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: alex
--

ALTER TABLE ONLY public."Plants"
    ADD CONSTRAINT "Plants_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."Users"(id);


--
-- PostgreSQL database dump complete
--

