"""empty message

Revision ID: 296f2e1df8b4
Revises: 49698057f44e
Create Date: 2020-01-08 15:29:32.150735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '296f2e1df8b4'
down_revision = '49698057f44e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('PlantInstance_plant_list_id_fkey',
                       'PlantInstance', type_='foreignkey')
    op.drop_column('PlantInstance', 'plant_list_id')
    op.drop_table('PlantList')
    op.add_column('PlantInstance', sa.Column(
        'date', sa.DateTime(), nullable=False))
    op.add_column('PlantInstance', sa.Column(
        'name', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PlantInstance', sa.Column('plant_list_id',
                                             sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('PlantInstance_plant_list_id_fkey',
                          'PlantInstance', 'PlantList', ['plant_list_id'], ['id'])
    op.drop_column('PlantInstance', 'name')
    op.drop_column('PlantInstance', 'date')
    op.create_table('PlantList',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        'nextval(\'"PlantList_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=120),
                              autoincrement=False, nullable=False),
                    sa.Column('date', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(length=1000),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='PlantList_pkey')
                    )
    # ### end Alembic commands ###
