"""empty message

Revision ID: 49698057f44e
Revises: 
Create Date: 2020-01-08 14:45:18.833898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49698057f44e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('latin_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=2500), nullable=False),
    sa.Column('image_link', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlantList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlantInstance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('plant_list_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=2500), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['Plant.id'], ),
    sa.ForeignKeyConstraint(['plant_list_id'], ['PlantList.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PlantInstance')
    op.drop_table('PlantList')
    op.drop_table('Plant')
    # ### end Alembic commands ###
