"""empty message

Revision ID: 5366394e4835
Revises: 296f2e1df8b4
Create Date: 2020-01-09 17:01:46.523927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5366394e4835'
down_revision = '296f2e1df8b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=2500), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['Plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('PlantInstance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PlantInstance',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"PlantInstance_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=2500), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['Plant.id'], name='PlantInstance_plant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='PlantInstance_pkey')
    )
    op.drop_table('Observations')
    # ### end Alembic commands ###
