"""empty message

Revision ID: e56742b7ec38
Revises: 19fcc623bd9e
Create Date: 2020-02-08 10:02:54.029146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56742b7ec38'
down_revision = '19fcc623bd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('latin_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=2500), nullable=False),
    sa.Column('image_link', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=2500), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['Plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Observations')
    op.drop_table('Plant')
    # ### end Alembic commands ###
